service: es-cloud

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-admin
  memorySize: 128
  stage: dev
  region: ap-southeast-2
  environment:
    EMAIL_SERVICE_API_KEY: KEYEXAMPLE1234

  iamRoleStatements:
    - Effect: "Allow"
      Action:
          - execute-api:Invoke
      Resource: "arn:aws:execute-api:ap-southeast-2:*:*"

functions:
  checkESCloud:
    handler: lambdafunctions/checkElasticsearchCloud.checkES
    environment:
      PASSWORD_ITERATIONS: 4096
      PASSWORD_DERIVED_KEY_LENGTH: 256
    events:
      - http:
          path: checkEs
          integration: lambda
          method: get
          cors: true
          request:
            Content-Type: "application/json"
            passThrough: NEVER
  createIndex:
    handler: lambdafunctions/createIndexElasticsearchCloud.createIndexES
    environment:
      PASSWORD_ITERATIONS: 4096
      PASSWORD_DERIVED_KEY_LENGTH: 256
    events:
      - http:
          path: createIndex/{indexName}
          integration: lambda
          method: post
          cors: true
          request:
            Content-Type: "application/json"
            passThrough: NEVER